### ISSUE TITLE
I2C Wiring of Shuttleboard

### ISSUE THREAD

**Issue by Casey10110** [BoschSensortec/BMP3-Sensor-API#1]

**Comment by Casey10110** [comment]
![img_2138](https://user-images.githubusercontent.com/39539364/43023185-cc70ed68-8c1e-11e8-97ac-c55893149565.jpeg)
![img_2137](https://user-images.githubusercontent.com/39539364/43023187-cc8dbfb0-8c1e-11e8-81ef-a83b4d5497c6.jpeg)

Hi guys,

I am using the I2C scanner for Arduino IDE (https://playground.arduino.cc/Main/I2cScanner) on an Adafruit Metro Express and can't get it to recognize the BMP388 at all. On an Arduino Uno I sometimes get it to work. I am using to 4.7k Ohm pull-up resistors on the SDA and SCL lines. Any idea why the MPL3115A2 alti on the upper image is recognized with the same wiring and the BMP388 is not? Is the wiring right? 

Thank you,
Casey

**Comment by BoschSensortec** [comment]
Hi @Casey10110,

The board is connected upside down. In addition, You need to supply both VDD and VDDIO. SDO is the I2C address select and should be connected to either VDDIO, or GND. The CSB pin should be tied to VDDIO.

**Comment by Casey10110** [comment]
Ha! I forgot about the upside down part, I actually ended up fixing that after I took these pictures, but I was getting the same results. Thank you SO MUCH for helping me out here, I will give that a try ...

**Comment by Casey10110** [comment]
OK, I am getting the same result when wired up (as I understand it) like in the datasheet, on both an Arduino Uno and an Adafruit Metro Express:

![img_2164](https://user-images.githubusercontent.com/39539364/43162484-0609aeb0-8f40-11e8-8112-0d9baeb43cb7.jpeg)
![img_2165](https://user-images.githubusercontent.com/39539364/43162485-0623140e-8f40-11e8-8bea-4a654f4c2624.jpeg)


Is this wiring right? What am I missing.

**Comment by BoschSensortec** [comment]
The line connected to A0 should be connected to 3.3V.

**Comment by Casey10110** [comment]
This still isn't working. I actually have two different shuttle boards from you guys and for one, it finds a device at every address, and with the other, it finds no devices with the following wiring:

![img_2177](https://user-images.githubusercontent.com/39539364/43230766-694fe30c-901e-11e8-81e9-0136a2f0e37b.jpeg)
![img_2175](https://user-images.githubusercontent.com/39539364/43230767-6b2fbfee-901e-11e8-9563-5402ed4ad3a4.jpeg)

Any more ideas?

**Comment by BoschSensortec** [comment]
Hi @Casey10110,

Please refer the connection table below,

| Shuttle pin number | Purpose | Connection in I2C |
| --- | --- | --- |
| 1 | VDD | 3.3V |
| 2 | VDDIO | 3.3V |
| 3 | GND | GND |
| 4 | SDO (I2C addr SEL) | GND or 3.3V |
| 5 | SDI | SDA |
| 6 | SCK | SCL |
| 7 | CSB | 3.3V |

In addition, make sure that you use a 3.3V board to communicate with the sensor as the sensor has a maximum voltage tolerance of 3.6V. Any I2C pull-ups would in addition have to be connected to 3.3V.

**Comment by Casey10110** [comment]
Frustrating, the wiring you describe there is exactly what I have on the top image and it still doesn't work. The board has 3.3v logic.

**Comment by BoschSensortec** [comment]
@Casey10110,

Could you modify the I2C scanner code regarding the transmission to,

```c
Wire.beginTransmission(address);
Wire.write(0x00);
error = Wire.endTransmission();
```

**Comment by Casey10110** [comment]
Super strange guys ... same exact result. I really appreciate you trying to help me here. I have no idea why it isn't working. I have two different BMP388 shuttleboards from you guys, and I am using two totally different boards to run it: UNO and METRO Express. Same result in every combination. Anybody else here had success with either of these boards? I can't get it to work.

**Comment by Casey10110** [comment]
Do you guys have any other ideas of why this isn't working ... nobody is chiming in here. Could it be that both boards are defective?

**Comment by Casey10110** [comment]
OK thank you very much for testing it. I guess I will have to buy another board and give it another shot. Perhaps I did end up damaging them.

**Comment by Casey10110** [comment]
OK, I bought another board, wired it up, and had the exact same result. This board never touched a 5V device, so it is a different problem. I suppose I will take this over to an Adafruit forum, as nothing seems to help over here and I am using a Metro Express M0.

**Comment by BoschSensortec** [comment]
Hi @Casey10110,

Have you already checked the continuity of the wires and the breadboard that you are using?
